[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; --- PREVENT DOWNLOAD MODE LOCKOUT ---
monitor_dtr = 0
monitor_rts = 0

; --- CRITICAL MEMORY SETTINGS ---
board_build.arduino.memory_type = qio_opi 

build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    links2004/WebSockets
    madhephaestus/ESP32Servo